# Hindsight Instruction Prediction from State Sequences (HIPSS)
name: 'hipss'

lr: 0.0003
batch_size: 32

# grad norm clipping
clip_grad_norm: True
# max norm for clipping critic grads
max_norm: 1

# encoder and decoder parameters
hidden_size: 128
dropout: 0.0
n_layers: 2

train_epochs: 1
train_freq: 2
# when the model is good enough to be used for hindsight learning
val_acc_threshold: 0.7
# size of the validation set
val_ratio: 0.2

# number of transitions to replay for each HI epsiode
replay_k: 2
# the replay strategy "episode" "future" "final"
# best results with "future" and "final"
replay_strategy: 'future'
