name: hipss
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.1.3
  - mpi4py=3.1.3
  - pytorch::pytorch
  - tensorboard=2.7.0
  - wandb=0.12.7
  - pip:
    - gym==0.21.0
    - pybullet==3.2.0
    - git+ssh://git@github.com/frankroeder/lanro-gym.git
